### ISSUE TITLE
Progress bar hangs when executing ./build.sh

### ISSUE THREAD

**Issue by SPRTANG** [smartscenes/sstk#13]
When executing `lerna bootstrap --hoist` script in package.json from main directory, progress bar hangs on ` \ install dependencies: info hoist Finished pruning hoiste`. Has anybody got solution to this issue? I am new to NodeJS.

**Comment by Zoe-Ziyi** [comment]
Hi, same problem. Did you solve it?

**Comment by hsl8856** [comment]
Hi, same problem. Did you solve it?
