### ISSUE TITLE
No server/static/data/nyuv2/nyuv2.scans.txt

### ISSUE THREAD

**Issue by Coldplayplay** [smartscenes/sstk#3]
As wiki said, you also need to update server/proj/scannet/tasks/segment_annotation/default.config.yml to point to the assets you want to annotate by updating the following fields:
```
scansToAnnotate: <filename of your file with list of scans that you people to annotate>
idPrefix: <your asset source>
```
[https://github.com/smartscenes/sstk/blob/dev/server/proj/scannet/tasks/segment_annotation/default.config.yml](https://github.com/smartscenes/sstk/blob/dev/server/proj/scannet/tasks/segment_annotation/default.config.yml)
But no nynu2 existence as reference

**Comment by msavva** [comment]
@Coldplayplay ,

Apologies for the long delay in responding to this issue. We have incorporated example files and some starter data.

Please pull the latest code and refer to the instructions in https://github.com/smartscenes/sstk/wiki/Preparing-assets-for-annotation#registering-your-assets .

Let us know if you experience any issues.

**Comment by Coldplayplay** [comment]
I have tried many times, but there is nothing shown in the web.I guess something went wrong in registering our assets.Hope a complete tutorial in wiki soon.

**Comment by msavva** [comment]
@Coldplayplay 

Can you try the following steps on the `dev` branch of the repository and let us know if there are any errors or issues that you observe:
1. Build the sstk `dev` branch using the `build.sh` script
1. Download the NYUv2 example data by running the `getexamples.sh` script
1. Run the server module using the `run.sh` script in `server`
1. Navigate to http://localhost:8010/scans/nyuv2

You should see a view showing one example scan and allowing for annotation (ignore the red message about no existing annotations).  If nothing shows up, open the Chrome developer tools console, refresh the URL and look for error messages.  Also look for messages on the terminal within which the server process is running.  Please follow up on this issue if you see any errors.

**Comment by Coldplayplay** [comment]
Sorry, I didn't notice you have already updated the nyuv2 examples. It's
all OK. Thank you very much.

2018-05-20 9:50 GMT+08:00 Manolis Savva <notifications@github.com>:
