### ISSUE TITLE
NYUV2 sample does not display in browser 

### ISSUE THREAD

**Issue by tdty1803** [smartscenes/sstk#40]
http://localhost:8010/scans/segment-annotator-single
When running the above annotator, the nyuv2 sample (nyuv2.bedroom_0114)
) No data is displayed.
What I did was sh build.sh, sh getexamples.sh, sh run.sh. The server creates the database "test" with mysql (ver5.7.36), and the table is created by executing stk / scripts / db / create_annotation_tables.sql.
scansToAnnotate: in defalut.config.yml has been changed to'../../../../static/data/nyuv2/nyuv2.example.csv'.
config.annDb of stk / server / config / index.js has been changed to the specified name created by mysql.
After executing sh run.sh, when segmentAnnotatorServer is opened in chrome, bedroom_0114 is not displayed as shown in the image below.
Please let me know if there are any missing parts in the settings.
![Screenshot from 2022-03-02 09-28-25](https://user-images.githubusercontent.com/100735226/156272041-b2b97ced-a6cc-40b8-b734-1024c3a73964.png)

**Comment by beibeirory** [comment]
Hi, I have the same problem. Have you resolved it? Thanks. @tdty1803

**Comment by tdty1803** [comment]
Hello, I haven't solved this problem yet. The environment uses Ubuntu 18.04, Python 3. I tried it on another PC, but it had the same symptoms. Thanks. @beibeirory

**Comment by ngnmai** [comment]
Hi, I have the same problem and still have not yet found a way to fix it. May I ask if you have found the way and how did you do it? 
Thank you alot! @tdty1803
