### ISSUE TITLE
Unable to load custom model for annotation

### ISSUE THREAD

**Issue by SreenivasVRao** [smartscenes/sstk#7]
I'm attaching the console log when I try to load my own .ply file with the Segment Annotator. Appreciate any help with this.

![image](https://user-images.githubusercontent.com/18532038/42543158-6756fe2a-845f-11e8-98be-f7481515c40a.png)

**Comment by SreenivasVRao** [comment]
Fixed. In the .json file for the custom dataset, you need to specify "surfaces",  "surfaces-finer",  "surfaces-finest" 

They can all be the same.

**Comment by oafolabi** [comment]
@SreenivasVRao  did you figure out how to use this toolkit? I have data fron Shapenet, Scannet, SUNCG etc, and I would just like to do a sample annotation and see were the results are saved.

**Comment by SreenivasVRao** [comment]
Hi, this was a while ago. Ultimately I went with a different approach, but I don't remember it very well anymore. Sorry. You might want to check out Open3D. http://www.open3d.org/
